apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  # this defines which part will be represented by this service
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  # this defines which part will be represented by this service
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  # this defines which part will be represented by this service
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30020
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # this defines which part will be represented by this service
  selector:
    app: fleetman-webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-port
      port: 27017
  type: ClusterIP
